RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy 172.0.0.0/8 10.0.0.0/8 192.168.0.0/16

SetEnvIf X-Forwarded-Proto "https" HTTPS=on

<IfModule mod_headers.c>
    <FilesMatch "^(index\.html|sw\.js)?$">
        Header set Cache-Control "no-cache, no-store, must-revalidate"
        Header set Pragma "no-cache"
        Header set Expires 0
    </FilesMatch>
</IfModule>
